### ISSUE TITLE
import path of hoge_test.go was not updated automaticaly

### ISSUE THREAD

**Issue by AkimuneKawa** [gostaticanalysis/skeleton#21]
ref: https://github.com/AkimuneKawa/calc_lcom/pull/1

## Environment
`go version go1.14.4 darwin/amd64`

## What I did & Problem
```
$ cd $GOPATH/src/github.com/AkimuneKawa
$ skeleton -path hoge
$ cd hoge
$ go mod init
$ go build
$ go test
# github.com/AkimuneKawa/hoge
package github.com/AkimuneKawa/hoge_test: package hoge is not in GOROOT (/usr/local/Cellar/go/1.14.4/libexec/src/hoge)
```

## How I fixed it
The import path of `hoge_test.go` should be like below.
```diff
- "hoge"
+ "github.com/AkimuneKawa/hoge"
```

**Comment by magnusbarata** [comment]
`go mod init`の時，`go mod init hoge`のようにパッケージを指定しないと確か`$GOROOT`で怒られた覚えがありました．
自分も初日に同様なミスをしたので，このような解決方法もありかもしれません．
`go.mod`がすでにある場合は，`rm -f go.mod`した後に，`go mod init hoge`で解決できました．

**Comment by AkimuneKawa** [comment]
@magnusbarata 
ありがとうございます！

実は、自分もその手法は試してみました。
そうすると、次は自作パッケージのimportでpackage is not in GOROOTと怒れられてしまったのですが、どう解決されましたか？

**Comment by tenntenn** [comment]
You should run without `-path` on `GOPATH`.
`GOPATH`上だと`-path`で指定する必要がないですね。
